### ISSUE TITLE
"Import declarations may only be declared at top level of a module" when running example app.

### ISSUE THREAD

**Issue by bcye** [react-gjs/renderer#283]
Hi,

I've tried to get the example code running with bundling using esbuild am getting this error when running it with gjs:
```
(gjs:119654): Gjs-CRITICAL **: 10:38:43.738: JS ERROR: SyntaxError: import declarations may only appear at top level of a module @ dist/out.js:17568:1

(gjs:119654): Gjs-CRITICAL **: 10:38:43.739: Script dist/out.js threw an exception
```

I'm running gjs 1.82.0 on Fedora 41 and have uploaded the code (including the bundled dist/out.js) to a [Github Repository](https://github.com/bcye/react-gjs-starter-template).

I'm running the (package.json) commands with bun but have also tried using npm and calling gjs from my terminal shell directly with the same issue.

Do you have an idea what I might be doing wrong?

Thanks :)

Edit I've noticed the quoting is around the --external as well, which might be the problem, though I didn't have success by changing the quoting yet

**Comment by ncpa0cpl** [comment]
I believe this is an issue with GJS itself, I remember I've also had this problem long ago and the only way to fix it back then was to move all the import statements to the very top of the file (I think). Though since then I had not run into this so I thought it was fixed.

You can try using this: https://github.com/react-gjs/react-gnome
It's a tool I've made around esbuild for building React apps specifically for GJS, it hoists all the import statements to the file top. It's currently not on npm but you should be able to clone it, build it and link install with `yarn link` or a equivalent bun or npm command. You can see a example config for this tool here: https://github.com/ncpa0cpl/untitled-slack-client/blob/master/react-gnome.config.mjs

**Comment by bcye** [comment]
Interesting, thank you I'll give it a shot :) I actually came across the react-gnome but thought it was a predecessor of this of sorts :D

**Comment by bcye** [comment]
Hey, react-gnome worked :)

I've tried to make a minimal example for getting started in the repository with some documentation, do you have any ideas/suggestions on what to add/improve?

**Comment by ncpa0cpl** [comment]
imo react-gnome needs docs the most, all the basics of how to use it and setup would be needed before I can publish it on npm, and that's really the most important thing to do next
